### ISSUE TITLE
dmenu.o failed?

### ISSUE THREAD

**Issue by nhercher** [2ion/dmenu-v#1]
In all honesty, I'm probably just being really stupid, but building this on Debian Jessie doesn't work for me, it gives me the output: 

cleaning
dmenu build options:
CFLAGS   = -std=c99 -pedantic -Wall -O3 -I/usr/X11R6/include -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="4.5V" -DXINERAMA
LDFLAGS  = -s -L/usr/X11R6/lib -lX11 -lXinerama
CC       = cc
CC -c dmenu.c
make: cc: Command not found
Makefile:18: recipe for target 'dmenu.o' failed
make: *** [dmenu.o] Error 127

after executing 'sudo make clean install'

UPDATE: just missing a few dev packages. Never mind.

**Comment by 2ion** [comment]
Exactly! You need to install gcc or another C compiler package first.
